# Generated by Django 3.2.9 on 2022-04-09 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='分类ID')),
                ('categoryName', models.CharField(max_length=100, verbose_name='分类名称')),
            ],
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='标签ID')),
                ('labelName', models.CharField(max_length=100, verbose_name='标签名称')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('name', models.CharField(max_length=25, verbose_name='用户名')),
                ('avatar', models.ImageField(null=True, upload_to='static/user', verbose_name='头像')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('pwd', models.CharField(max_length=255, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='帖子ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('summary', models.CharField(max_length=100, null=True, verbose_name='简要')),
                ('content', models.CharField(max_length=15000, verbose_name='内容')),
                ('author', models.CharField(default='Owr', max_length=20, verbose_name='作者')),
                ('publishTime', models.DateField(auto_now_add=True, verbose_name='发布时间')),
                ('read_counts', models.IntegerField(default=0, verbose_name='阅读数')),
                ('comment_counts', models.IntegerField(default=0, verbose_name='评论数')),
                ('like_counts', models.IntegerField(default=0, verbose_name='喜欢数')),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.categorys', verbose_name='分类ID')),
                ('labelId', models.ManyToManyField(to='web.Labels', verbose_name='标签ID')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='点赞ID')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.posts', verbose_name='帖子ID')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.users', verbose_name='用户ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论ID')),
                ('comment', models.CharField(max_length=255, verbose_name='评论内容')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.posts', verbose_name='帖子ID')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.users', verbose_name='用户ID')),
            ],
        ),
    ]
