# Generated by Django 3.2.9 on 2022-03-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('name', models.CharField(max_length=25, null=True, verbose_name='用户名')),
                ('avatar', models.ImageField(null=True, upload_to='static/user', verbose_name='头像')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('pwd', models.CharField(max_length=255, null=True, verbose_name='密码')),
            ],
        ),
    ]
