# Generated by Django 3.2.9 on 2022-04-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='labelId',
            field=models.ManyToManyField(blank=True, to='web.Labels', verbose_name='标签ID'),
        ),
    ]
