# Generated by Django 3.2.9 on 2022-04-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_posts_labelid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='图集ID')),
                ('imgPath', models.ImageField(null=True, upload_to='static/picture', verbose_name='图片')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('summary', models.CharField(max_length=255, verbose_name='简要')),
                ('isCover', models.BooleanField(default=False, verbose_name='是否为封面')),
            ],
        ),
    ]
