# Generated by Django 3.2.9 on 2022-04-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='isDel',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
