# Generated by Django 3.2.9 on 2022-04-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_posts_isdel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='isCover',
        ),
        migrations.AddField(
            model_name='pictures',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='序号'),
            preserve_default=False,
        ),
    ]
