# Generated by Django 3.2.9 on 2022-05-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20220430_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('s', 'superuser'), ('u', 'user'), ('v', 'visitor')], default='u', max_length=2),
        ),
    ]
