# Generated by Django 3.2.9 on 2022-05-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='loginTime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='电话'),
        ),
    ]
