# Generated by Django 3.2.9 on 2022-05-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20220506_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default='2022-5-6 12:03:12', verbose_name='评论时间'),
            preserve_default=False,
        ),
    ]
