# Generated by Django 3.2.9 on 2022-05-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20220508_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='user/avatar.jpg', upload_to='static/user', verbose_name='头像'),
        ),
    ]
