# Generated by Django 3.2.9 on 2022-05-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='图集ID')),
                ('imgPath', models.ImageField(null=True, upload_to='static/picture', verbose_name='图片')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('summary', models.CharField(max_length=255, verbose_name='简要')),
                ('sort', models.IntegerField(verbose_name='序号')),
            ],
        ),
    ]
