# Generated by Django 3.2.9 on 2022-05-08 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('name', models.CharField(max_length=25, verbose_name='用户名')),
                ('avatar', models.ImageField(default='static/user/avatar.jpg', upload_to='static/user', verbose_name='头像')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='电话')),
                ('pwd', models.CharField(max_length=255, verbose_name='密码')),
                ('loginTime', models.DateField(null=True)),
                ('role', models.CharField(choices=[('s', 'superuser'), ('u', 'user'), ('v', 'visitor')], default='u', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='点赞ID')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.posts', verbose_name='帖子ID')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users', verbose_name='用户ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论ID')),
                ('comment', models.CharField(max_length=255, verbose_name='评论内容')),
                ('time', models.DateTimeField(verbose_name='评论时间')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.posts', verbose_name='帖子ID')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users', verbose_name='用户ID')),
            ],
        ),
    ]
